name: Calculated Risk Motorcycle Group
favicon: null
layout_spectrum: 0.568119088653475
typography_spectrum: 0.1822392283938825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.15168266370892525
  lightness: 0.5599061569664627
  saturation: 0.20473454450257123
  rhythmicContrast: 0.13574286620132625
purpose: []
